FROM mysql:8.0

#contraseña del usuario root
ENV MYSQL_ROOT_PASSWORD root
#nombre de la base de datos 
ENV MYSQL_DATABASE practica_contenedores
#nombre del usuario
ENV MYSQL_USER user
#contraseña del usuario
ENV MYSQL_PASSWORD password
#puerto por defecto de mysql
EXPOSE 3306